// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ChessComRatingSnapshot struct {
	ID           int64              `json:"id"`
	UserID       int64              `json:"user_id"`
	CapturedAt   pgtype.Timestamptz `json:"captured_at"`
	BulletRating pgtype.Int4        `json:"bullet_rating"`
	BlitzRating  pgtype.Int4        `json:"blitz_rating"`
	RapidRating  pgtype.Int4        `json:"rapid_rating"`
	DailyRating  pgtype.Int4        `json:"daily_rating"`
}

type Puzzle struct {
	ID        int64              `json:"id"`
	GameUuid  pgtype.UUID        `json:"game_uuid"`
	UserID    int64              `json:"user_id"`
	Puzzle    []byte             `json:"puzzle"`
	Status    string             `json:"status"`
	Comment   pgtype.Text        `json:"comment"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	SolvedAt  pgtype.Timestamptz `json:"solved_at"`
}

type User struct {
	ID               int64              `json:"id"`
	Email            string             `json:"email"`
	PasswordHash     string             `json:"password_hash"`
	ChessComUsername string             `json:"chess_com_username"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}
