// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Puzzle struct {
	ID      int64       `json:"id"`
	UserID  int64       `json:"user_id"`
	Puzzle  []byte      `json:"puzzle"`
	Status  string      `json:"status"`
	Comment pgtype.Text `json:"comment"`
}

type User struct {
	ID               int64  `json:"id"`
	Email            string `json:"email"`
	PasswordHash     string `json:"password_hash"`
	ChessComUsername string `json:"chess_com_username"`
}
