// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: puzzles.sql

package db

import (
	"context"
)

const addPuzzle = `-- name: AddPuzzle :one


SELECT id, game_uuid, user_id, puzzle, status, comment, created_at, solved_at FROM puzzles 
WHERE user_id = $1
`

// INSERT INTO puzzles
func (q *Queries) AddPuzzle(ctx context.Context, userID int64) (Puzzle, error) {
	row := q.db.QueryRow(ctx, addPuzzle, userID)
	var i Puzzle
	err := row.Scan(
		&i.ID,
		&i.GameUuid,
		&i.UserID,
		&i.Puzzle,
		&i.Status,
		&i.Comment,
		&i.CreatedAt,
		&i.SolvedAt,
	)
	return i, err
}

const getPuzzleStats = `-- name: GetPuzzleStats :one
SELECT 
    COUNT(*) FILTER (WHERE status = 'solved') AS solved,
    COUNT(*) FILTER (WHERE status <> 'solved') AS unsolved,
    COUNT(*) AS total
FROM puzzles 
WHERE user_id = $1
`

type GetPuzzleStatsRow struct {
	Solved   int64 `json:"solved"`
	Unsolved int64 `json:"unsolved"`
	Total    int64 `json:"total"`
}

func (q *Queries) GetPuzzleStats(ctx context.Context, userID int64) (GetPuzzleStatsRow, error) {
	row := q.db.QueryRow(ctx, getPuzzleStats, userID)
	var i GetPuzzleStatsRow
	err := row.Scan(&i.Solved, &i.Unsolved, &i.Total)
	return i, err
}
