// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: puzzles.sql

package db

import (
	"context"
)

const addPuzzle = `-- name: AddPuzzle :one


SELECT id, game_uuid, user_id, puzzle, status, comment, created_at, solved_at FROM puzzles 
WHERE user_id = $1
`

// INSERT INTO puzzles
func (q *Queries) AddPuzzle(ctx context.Context, userID int64) (Puzzle, error) {
	row := q.db.QueryRow(ctx, addPuzzle, userID)
	var i Puzzle
	err := row.Scan(
		&i.ID,
		&i.GameUuid,
		&i.UserID,
		&i.Puzzle,
		&i.Status,
		&i.Comment,
		&i.CreatedAt,
		&i.SolvedAt,
	)
	return i, err
}
